version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  oracle-lab:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-lab
    restart: always
    environment:
      ORACLE_PWD: 1234
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-oracle.sql:/opt/oracle/scripts/startup/init-oracle.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/1234@//localhost:1521/XE", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
  oracle_data:
